# -*- coding: utf-8 -*-
"""yaqith_sentinel.model.training.script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XuwGuvp1RiHT1r4jDtkc9zf34AdGlPdP
"""

"""

YAQITH Sentinel - Model Training Script



"""



import os

import json

import joblib

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import classification_report, confusion_matrix

DATA_PATH = "/content/yaqith_sentinel_synthetic_logins 2.xlsx"

MODEL_DIR = "models"

MODEL_PATH = os.path.join(MODEL_DIR, "yaqith_sentinel_rf.joblib")

FEATURES_PATH = os.path.join(MODEL_DIR, "yaqith_features.json")

NUMERIC_FEATURES = [

    "is_vpn",

    "is_new_device",

    "is_new_city",

    "distance_from_last_login_km",

    "hour_of_day",

    "weekday",

    "failed_logins_last_24h",

    "typing_speed_cps",

    "nav_pattern_similarity",

    "session_duration_sec",

    "past_compromised_account",

]

TARGET_COL = "is_attack_label"

def load_data(path: str) -> pd.DataFrame:



    if not os.path.exists(path):

        raise FileNotFoundError(f"لم يتم العثور على الملف: {path}")

    df = pd.read_csv(path)

    return df



def preprocess(df: pd.DataFrame) -> pd.DataFrame:


    missing = [col for col in NUMERIC_FEATURES + [TARGET_COL] if col not in df.columns]

    if missing:

        raise ValueError(f"هذه الأعمدة ناقصة في البيانات: {missing}")

df_proc = df.copy()

    for col in NUMERIC_FEATURES + [TARGET_COL]:

        df_proc[col] = pd.to_numeric(df_proc[col], errors="coerce")

df_proc = df_proc.dropna(subset=NUMERIC_FEATURES + [TARGET_COL])



    return df_proc



def train_model(df: pd.DataFrame) -> RandomForestClassifier:

    """تدريب نموذج RandomForest وإرجاعه."""

    X = df[NUMERIC_FEATURES]

    y = df[TARGET_COL]


    X_train, X_test, y_train, y_test = train_test_split(

        X, y, test_size=0.25, random_state=42, stratify=y

    )



    model = RandomForestClassifier(

        n_estimators=200,

        max_depth=None,

        random_state=42,

        class_weight="balanced",

        n_jobs=-1

    )


    model.fit(X_train, y_train)




    y_pred = model.predict(X_test)

    print("=== Confusion Matrix ===")

    print(confusion_matrix(y_test, y_pred))

    print("\n=== Classification Report ===")

    print(classification_report(y_test, y_pred, digits=3))



    return model

def save_artifacts(model: RandomForestClassifier):

    """حفظ المودل وقائمة الأعمدة في مجلد models/."""

    os.makedirs(MODEL_DIR, exist_ok=True)




    joblib.dump(model, MODEL_PATH)

    print(f"تم حفظ المودل في: {MODEL_PATH}")





    with open(FEATURES_PATH, "w", encoding="utf-8") as f:

        json.dump({"numeric_features": NUMERIC_FEATURES}, f, ensure_ascii=False, indent=2)

import os
import pandas as pd


def load_data(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(f"لم يتم العثور على الملف: {path}")
    df = pd.read_excel(path)
    return df

def main():
    print("1) قراءة البيانات...")
    df = load_data(DATA_PATH)

    print("2) تجهيز البيانات...")
    df_proc = preprocess(df)

    print(f"عدد السجلات بعد التنظيف: {len(df_proc)}")

    print("3) تدريب المودل...")
    model = train_model(df_proc)

    print("4) حفظ المخرجات...")
    save_artifacts(model)
    print("\n تم تدريب المودل وحفظه بنجاح.")

if __name__ == "__main__":
    main()